vim.cursorline=true
vim.opt.tabstop = 2
vim.opt.autoindent = true
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.expandtab = true
vim.opt.hlsearch = false
vim.opt.incsearch = true
vim.opt.smartindent = true
vim.opt.cmdheight=2
vim.opt.mouse='a'
vim.opt.wrap = false
vim.opt.number=true
vim.opt.smarttab=true
vim.g.mapleader = " "
vim.opt.hlsearch = false
vim.opt.incsearch = true
vim.g.go_asmfmt_autosave = 0
